name: Node.js CI

on:
  push:
    branches: [ "main" ] # Triggers workflow on main branch push

jobs:
  build:
    runs-on: self-hosted # Runner environment: self-hosted machine

    strategy:
      matrix:
        node-version: [22.x] # Node.js version to use

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Setup Node.js with caching
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      # Step 3: Install Dependencies
      - name: Install dependencies
        run: npm ci

      # Step 4: Deploy files to EC2
      - name: Deploy to EC2
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.EC2_HOST }}       # EC2 public IP
          username: ${{ secrets.EC2_USER }}   # Username, e.g., 'ubuntu' or 'ec2-user'
          key: ${{ secrets.EC2_SSH_KEY }}     # SSH private key
          source: "."                         # Source directory (root of repo)
          target: "/home/${{ secrets.EC2_USER }}/app" # Target directory on EC2

      # Step 5: SSH into EC2 and Start/Restart Application
      - name: SSH into EC2 and Start Application
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/${{ secrets.EC2_USER }}/app
            npm install
            pm2 restart app || pm2 start app.js --name "app"
            sudo systemctl restart nginx
